services:
  postgresql:
    image: postgres:16
    container_name: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expresstasks
    ports:
      - 5432:5432